PRODUCT_VERSION_MAJOR = 19
PRODUCT_VERSION_MINOR = 1
# Increase Exodus Version with each major release.
PRODUCT_VERSION_ANDROID = 12.1
PRODUCT_EXODUS_VERSION = squirrel

# Internal version
LINEAGE_VERSION := ExodusOS-$(PRODUCT_VERSION_ANDROID)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-$(PRODUCT_EXODUS_VERSION)

# Display version
LINEAGE_DISPLAY_VERSION := ExodusOS-$(PRODUCT_VERSION_ANDROID)-$(LINEAGE_BUILD)-$(PRODUCT_EXODUS_VERSION)
